//probably wont use this....
//This model is only to enable faster viewing of objects generated by 
//the omdb movies api which only allows me 1000 requests/day which with searches
//and long lists of stuff would maybe get used up, so I am
//in here storing movie objects and movie omdb ids
//any movie added to a favorites list, reviewed by a user, or on a user's wishlist
//will be added to this model if not already there.
const mongoose = require("mongoose");
const Schema = mongoose.Schema;


const movieSchema = new Schema({
    OMDBid: String,
    objectFromOMDB: {type: Schema.Types.Object},
    reviewsByMyUsers: [{type: Schema.Types.Object}],
    //need to be sure to have a review delete that pulls these back out
},
{
    timestamps: {
      createdAt: 'created_at',
      updatedAt: 'updated_at'
      //can also just put timestamps: true
    }
  });


const Movie = mongoose.model("Movie", movieSchema);

module.exports = Movie;